version = 1
SPDX-PackageName = "FreeIAM"
SPDX-PackageSupplier = "Florian Best <info@freeiam.org>"
SPDX-PackageDownloadLocation = "https://www.freeiam.org/"

[[annotations]]
path = [ "src/**/*.py", "docs/examples/*.py", "tests/**/*.py" , "benchmarks/**/*.py" ]
SPDX-FileCopyrightText = "2025 Florian Best <info@freeiam.org>"
SPDX-License-Identifier = "MIT OR Apache-2.0"

[[annotations]]
path = [
 "docs/**/*.rst",
 "docs/conf.py",
 "*.md",
 ".gitignore",
 "tox.ini",
 "**/pyproject.toml",
 "pytest.ini",
 "pytest_benchmark.ini",
 "**/Makefile",
 "*.yml",
 "*.yaml",
 "**/requirements.txt",
 "*.toml",
 "tests/certs/*",
 ".github/workflows/*.yml",
]
SPDX-FileCopyrightText = "2025 Florian Best <info@freeiam.org>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [ "stubs/pyasn1/**/*.pyi" ]
SPDX-FileCopyrightText = "2005-2020, Ilya Etingof <etingof@gmail.com>"
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = [ "stubs/ldap/**/*.pyi", "stubs/_ldap.pyi", "stubs/ldapurl.pyi", "stubs/ldif.pyi" ]
SPDX-FileCopyrightText = "python-ldap"
SPDX-License-Identifier = "LicenseRef-python-ldap AND MIT"
